### ISSUE TITLE
System.IO.Exception in Ch10

### ISSUE THREAD

**Issue by knilecrack** [markjprice/cs6dotnetcore#1]
if you run into access denied, being used by another process issue in this code
`string xmlFile = @"e:\Projects\Visual Studio Projects\Ch10_FileSystem\Ch10_Streams.xml";
            FileStream xmlFileStream = File.Create(xmlFile);
            XmlWriter xml = XmlWriter.Create(xmlFileStream, new XmlWriterSettings { Indent = true });

```
        // write the XML declaration
        xml.WriteStartDocument();

        // write a root element
        xml.WriteStartElement("callsigns");

        // enumerate the strings writing each one to the stream
        foreach (string item in callsigns)
        {
            xml.WriteElementString("callsign", item);
        }

        // write the close root element
        xml.WriteEndElement();
        xml.Dispose();

        // output all the contents of the file to the Console
        WriteLine($"{xmlFile} contains {new FileInfo(xmlFile).Length} bytes.");
        WriteLine(File.ReadAllText(xmlFile));`
```

you have to xmlFileStream.Close();

**Comment by markjprice** [comment]
Good catch. Yes, it's always good practice to explicitly Close (in .NET Framework) or Dispose (in .NET Core) when you are done with unmanaged objects such as files. Thanks!
